Applications/MPExtended.Applications.WebMediaPortal/Controllers/TVShowsLibraryController.cs
#region Copyright (C) 2012-2013 MPExtended, 2020 Team MediaPortal
// Copyright (C) 2012-2013 MPExtended Developers, http://www.mpextended.com/
// Copyright (C) 2020 Team MediaPortal, http://www.team-mediaportal.com/
// 
// MPExtended is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 2 of the License, or
// (at your option) any later version.
// 
// MPExtended is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with MPExtended. If not, see <http://www.gnu.org/licenses/>.
#endregion

using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Web;
using System.Web.Mvc;
using MPExtended.Applications.WebMediaPortal.Code;
using MPExtended.Applications.WebMediaPortal.Models;
using MPExtended.Libraries.Service;
using MPExtended.Services.Common.Interfaces;
using MPExtended.Services.MediaAccessService.Interfaces;
using MPExtended.Services.MediaAccessService.Interfaces.TVShow;
using MPExtended.Services.StreamingService.Interfaces;

namespace MPExtended.Applications.WebMediaPortal.Controllers
{
  [ServiceAuthorize]
  public class TVShowsLibraryController : BaseController
  {
    // Series
    public ActionResult Index(string filter = null)
    {
      var shows = Connections.Current.MAS.GetTVShowsDetailed(Settings.ActiveSettings.TVShowProvider, filter, WebSortField.Title, WebSortOrder.Asc)
          .Where(x => !String.IsNullOrEmpty(x.Title));
      return View(shows);
    }

    public ActionResult ShowInfo(string show)
    {
      var model = new TVShowViewModel(show);
      if (model.Show == null)
        return HttpNotFound();
      return Json(model, JsonRequestBehavior.AllowGet);
    }

    public ActionResult SeriesFanart(string show, int width = 0, int height = 0, int num = -1)
    {
      return Images.ReturnFromService(WebMediaType.TVShow, show, WebFileType.Backdrop, width, height, "Images/default/tvshow-fanart.png", num);
    }

    public ActionResult SeriesPoster(string show, int width = 0, int height = 0)
    {
      return Images.ReturnFromService(WebMediaType.TVShow, show, WebFileType.Poster, width, height, "Images/default/tvshow-poster.png");
    }

    public ActionResult SeriesBanner(string show, int width = 0, int height = 0)
    {
      return Images.ReturnFromService(WebMediaType.TVShow, show, WebFileType.Banner, width, height, "Images/default/tvshow-banner.png");
    }

    // Seasons
    public ActionResult Seasons(string show)
    {
      var model = new TVShowViewModel(show);
      if (model.Show == null)
        return HttpNotFound();

      return View(model);
    }

    public ActionResult SeasonInfo(string season)
    {
      var model = new TVSeasonViewModel(season);
      if (model.Season == null)
        return HttpNotFound();
      return Json(model, JsonRequestBehavior.AllowGet);
    }

    public ActionResult SeasonImage(string season, int width = 0, int height = 0)
    {
      return Images.ReturnFromService(WebMediaType.TVSeason, season, WebFileType.Banner, width, height, "Images/default/tvseason-banner.png");
    }

    // Episodes
    public ActionResult Episodes(string season)
    {
      var model = new TVSeasonViewModel(season);
      if (model.Season == null)
        return HttpNotFound();

      return View(model);
    }

    public ActionResult Details(string episode)
    {
      var model = new TVEpisodeViewModel(episode);
      if (model.Episode == null)
        return HttpNotFound();

      ViewBag.ShowPlay = model.Episode.Path.Count > 0;
      return View(model);
    }

    public ActionResult EpisodeInfo(string episode)
    {
      var model = new TVEpisodeViewModel(episode);
      if (model.Episode == null)
        return HttpNotFound();
      return Json(model, JsonRequestBehavior.AllowGet);
    }

    public ActionResult Play(string episode)
    {
      var model = new TVEpisodeViewModel(episode);
      if (model.Episode == null)
        return HttpNotFound();

      return View(model);
    }

    public ActionResult EpisodeImage(string episode, int width = 0, int height = 0)
    {
      return Images.ReturnFromService(WebMediaType.TVEpisode, episode, WebFileType.Banner, width, height, "Images/default/tvepisode-banner.png");
    }

    // Genres
    public ActionResult Genres(string filter = null)
    {
      var genres = Connections.Current.MAS.GetTVShowGenres(Settings.ActiveSettings.TVShowProvider, filter, WebSortField.Title, WebSortOrder.Asc)
          .Where(x => !String.IsNullOrEmpty(x.Title));
      return View(genres);
    }

    public ActionResult Genre(string genre)
    {
      var model = new TVShowGenreViewModel(genre);
      if (model.Genre == null)
        return HttpNotFound();

      return View(model);
    }

    public ActionResult GenreCover(string genre, int width = 0, int height = 0)
    {
      return Images.ReturnFromService(WebMediaType.TVShowGenre, genre, WebFileType.Cover, width, height, "Images/default/genre-cover.png");
    }

    public ActionResult GenreFanart(string genre, int width = 0, int height = 0, int num = -1)
    {
      return Images.ReturnFromService(WebMediaType.TVShowGenre, genre, WebFileType.Backdrop, width, height, "Images/default/genre-fanart.png", num);
    }

    // Actors
    public ActionResult Actors(string filter = null)
    {
      var actors = Connections.Current.MAS.GetTVShowActors(Settings.ActiveSettings.TVShowProvider, filter, WebSortField.Title, WebSortOrder.Asc)
          .Where(x => !String.IsNullOrEmpty(x.Title));
      return View(actors);
    }

    public ActionResult Actor(string actor)
    {
      var model = new TVShowActorViewModel(actor);
      if (model.Actor == null)
        return HttpNotFound();

      return View(model);
    }

    public ActionResult ActorCover(string actor, int width = 0, int height = 0)
    {
      return Images.ReturnFromService(WebMediaType.TVShowActor, actor, WebFileType.Cover, width, height, "Images/default/tvactor-cover.png");
    }

    public ActionResult ActorFanart(string actor, int width = 0, int height = 0, int num = -1)
    {
      return Images.ReturnFromService(WebMediaType.TVShowActor, actor, WebFileType.Backdrop, width, height, "Images/default/tvactor-fanart.png", num);
    }

  }
}

Applications/MPExtended.Applications.WebMediaPortal/Views/TVShowsLibrary/Details.cshtml
@model TVEpisodeViewModel
@{
    ViewBag.Title = @Model.Episode.Title;
}

<h2>@Model.Episode.Title</h2>

<div class="imageColumn">
    <img src="@Url.Action("EpisodeImage", new { episode = @Model.Episode.Id, width = 300 })" width="300" alt="No image" />
</div>
<div class="dataColumn">
    <ul>
        <li>@UIStrings.WrittenBy
            <ul>
                @foreach (string writer in Model.Episode.Writers)
                {
                    <li>@writer</li>
                }
            </ul>
        </li>

        <li>@UIStrings.GuestStarring
            <ul>
                @foreach (string guestStar in Model.Episode.GuestStars)
                {
                    <li>@guestStar</li>
                }
            </ul>        
        </li>

        <li>@String.Format(UIStrings.Aired, Model.Episode.FirstAired.ToShortDateString())</li>

        @if(ViewBag.ShowPlay) {
            <li>@Model.FullQuality</li>
            <li>@Html.ActionLink(UIStrings.Download, "Download", "Stream", Skin.GetDownloadArguments(Model.Episode.Type, Model.Episode.Id), new { })</li>
            <li>@Html.ActionLink(UIStrings.Play, "Play", new { episode = Model.Episode.Id })</li>
        }
    </ul>
</div>

<div class="textColumn">
    @Model.Episode.Summary
</div>

Applications/MPExtended.Applications.WebMediaPortal/Views/TVShowsLibrary/Episodes.cshtml
@model TVSeasonViewModel
@{
    var header = Model.Season.SeasonNumber == 0 ? 
        String.Format("{0} {1}", Model.Show.Title, UIStrings.Specials) : 
        String.Format(UIStrings.ShowSeason, Model.Show.Title, Model.Season.SeasonNumber);
    ViewBag.Title = header;    
}

<h2>@header</h2>

<div class="imageColumn">
    <img src="@Url.Action("SeasonImage", new { season = @Model.Season.Id, width = 500 })" width="500" alt="No image" />
</div>

<div class="listColumn">
    <ul>
        @foreach (var episode in Model.Episodes)
        {
            <li>@Html.ActionLink(String.Format(UIStrings.EpisodeDisplay, episode.EpisodeNumber, episode.Title), "Details", new { episode = episode.Id })</li>   
        }
    </ul>
</div>

Applications/MPExtended.Applications.WebMediaPortal/Views/TVShowsLibrary/Index.cshtml
@model IEnumerable<MPExtended.Services.MediaAccessService.Interfaces.TVShow.WebTVShowDetailed>
@{
	ViewBag.Title = UIStrings.TVShows;
}

<h2>@UIStrings.YourTVShows</h2>

<div id="slider" style="clear:both;float:left"></div>

@{ 
    var count = 0;
    var pages = 1;
}

<div class="paged-data-container">

    @foreach (var show in Model)
    {
        if ((count % MPExtended.Applications.WebMediaPortal.Code.Settings.ActiveSettings.PageSize) == 0)
        {
            if (count > 0) { pages++; }
        }
        count++;
        
        <div class="@("page" + pages.ToString())"  style="float: left;">
            <div style="padding: 0px 5px 0px 5px;">
                <a href="@Url.Action("Seasons", "TVShowsLibrary", new { show = show.Id })">
                    <span style="width:300px;height:150px" class="async-image-display" data-src="@Url.Action("SeriesBanner", new { show = @show.Id, width = 300 })"></span>
                </a>
            </div>
            <div style="text-align: center; padding-bottom: 20px;">@Html.ActionLink(show.Title, "Seasons", new { show = show.Id })</div>       
        </div>
    }
</div>


@Html.jQuery().EnableRangeSlider(pages, "#slider", UIStrings.SelectPage)
@Html.jQuery().EnableImageLoading();

Applications/MPExtended.Applications.WebMediaPortal/Views/TVShowsLibrary/Play.cshtml
@model TVEpisodeViewModel
@{
    ViewBag.Title = String.Format(UIStrings.WatchingEpisode, Model.Episode.Title, Model.Show.Title);
}

<h2>@UIStrings.Play</h2>
@Html.Raw(String.Format(UIStrings.YouAreWatchingEpisode, Model.Show.Title, Model.Season.SeasonNumber, Model.Episode.EpisodeNumber, Model.Episode.Title))
<br /><br />

@{Html.RenderAction("Player", "Stream", new
  {
      type = MPExtended.Services.Common.Interfaces.WebMediaType.TVEpisode,
      itemId = @Model.Episode.Id
  });
}

Applications/MPExtended.Applications.WebMediaPortal/Views/TVShowsLibrary/Seasons.cshtml
@model TVShowViewModel
@{
    ViewBag.Title = Model.Show.Title;
}

<h2>@Model.Show.Title</h2>

<div class="imageColumn extended">
    <img src="@Url.Action("SeriesPoster", new { show = Model.Show.Id, width = 500 })" width="500" alt="No image" />
</div>

<div>
    @foreach (var season in Model.Seasons)
    {
        <div class="seasonWrap" style="float: left; padding: 10px;">
            <a href="@Url.Action("Episodes", new { season = season.Id })">
                <img class="seasonPoster" src="@Url.Action("SeasonImage", new { season = season.Id, width = 100 })" width="100" alt="No image" />
            </a>
            <a style="text-align: center;" href="@Url.Action("Episodes", new { season = season.Id })">
                <div class="seasonTitle">@String.Format(season.SeasonNumber == 0 ? UIStrings.Specials : UIStrings.Season, season.SeasonNumber)<br />@season.Year</div>
            </a>
        </div>
    }
</div>