Applications/MPExtended.Applications.WebMediaPortal/Controllers/MovieLibraryController.cs
#region Copyright (C) 2012-2013 MPExtended, 2020 Team MediaPortal
// Copyright (C) 2012-2013 MPExtended Developers, http://www.mpextended.com/
// Copyright (C) 2020 Team MediaPortal, http://www.team-mediaportal.com/
// 
// MPExtended is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 2 of the License, or
// (at your option) any later version.
// 
// MPExtended is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with MPExtended. If not, see <http://www.gnu.org/licenses/>.
#endregion

using System;
using System.Linq;
using System.Web.Mvc;

using MPExtended.Services.Common.Interfaces;
using MPExtended.Applications.WebMediaPortal.Code;
using MPExtended.Applications.WebMediaPortal.Models;

namespace MPExtended.Applications.WebMediaPortal.Controllers
{
  [ServiceAuthorize]
  public class MovieLibraryController : BaseController
  {
    //
    // GET: /MovieLibrary/
    public ActionResult Index(string filter = null)
    {
      var movieList = Connections.Current.MAS.GetMoviesDetailed(Settings.ActiveSettings.MovieProvider, filter, WebSortField.Title, WebSortOrder.Asc);
      return View(movieList.Where(x => !String.IsNullOrEmpty(x.Title)).Select(x => new MovieViewModel(x)));
    }

    public ActionResult Details(string movie)
    {
      var model = new MovieViewModel(movie);
      if (model.Movie == null)
        return HttpNotFound();
      return View(model);
    }

    [HttpGet]
    public ActionResult MovieInfo(string movie)
    {
      var model = new MovieViewModel(movie);
      if (model.Movie == null)
        return HttpNotFound();
      return Json(model, JsonRequestBehavior.AllowGet);
    }

    public ActionResult Play(string movie)
    {
      var model = new MovieViewModel(movie);
      if (model.Movie == null)
        return HttpNotFound();
      return View(model);
    }

    public ActionResult Cover(string movie, int width = 0, int height = 0)
    {
      return Images.ReturnFromService(WebMediaType.Movie, movie, WebFileType.Cover, width, height, "Images/default/movie-cover.png");
    }

    public ActionResult Fanart(string movie, int width = 0, int height = 0, int num = -1)
    {
      return Images.ReturnFromService(WebMediaType.Movie, movie, WebFileType.Backdrop, width, height, "Images/default/movie-fanart.png", num);
    }

    public ActionResult Logo(string movie, int width = 0, int height = 0)
    {
      return Images.ReturnFromService(WebMediaType.Movie, movie, WebFileType.Logo, width, height, "Images/default/movie-logo.png");
    }

    // Actors
    public ActionResult Actors(string filter = null)
    {
      var actors = Connections.Current.MAS.GetMovieActors(Settings.ActiveSettings.MovieProvider, filter, WebSortField.Title, WebSortOrder.Asc)
          .Where(x => !String.IsNullOrEmpty(x.Title));
      return View(actors);
    }

    public ActionResult Actor(string actor)
    {
      var model = new MovieActorViewModel(actor);
      if (model.Actor == null)
        return HttpNotFound();

      return View(model);
    }

    public ActionResult ActorCover(string actor, int width = 0, int height = 0)
    {
      return Images.ReturnFromService(WebMediaType.MovieActor, actor, WebFileType.Cover, width, height, "Images/default/actor-cover.png");
    }

    public ActionResult ActorFanart(string actor, int width = 0, int height = 0, int num = -1)
    {
      return Images.ReturnFromService(WebMediaType.MovieActor, actor, WebFileType.Backdrop, width, height, "Images/default/actor-fanart.png", num);
    }

    // Collection
    public ActionResult Collections(string filter = null)
    {
      var collection = Connections.Current.MAS.GetCollections(Settings.ActiveSettings.MovieProvider, filter, WebSortField.Title, WebSortOrder.Asc)
          .Where(x => !String.IsNullOrEmpty(x.Title));
      return View(collection);
    }

    public ActionResult Collection(string collection)
    {
      var model = new CollectionViewModel(collection);
      if (model.Collection == null)
        return HttpNotFound();

      return View(model);
    }

    public ActionResult CollectionCover(string collection, int width = 0, int height = 0)
    {
      return Images.ReturnFromService(WebMediaType.Collection, collection, WebFileType.Cover, width, height, "Images/default/collection-cover.png");
    }

    public ActionResult CollectionFanart(string collection, int width = 0, int height = 0, int num = -1)
    {
      return Images.ReturnFromService(WebMediaType.Collection, collection, WebFileType.Backdrop, width, height, "Images/default/collection-fanart.png", num);
    }

    // Genres
    public ActionResult Genres(string filter = null)
    {
      var genres = Connections.Current.MAS.GetMovieGenres(Settings.ActiveSettings.MovieProvider, filter, WebSortField.Title, WebSortOrder.Asc)
          .Where(x => !String.IsNullOrEmpty(x.Title));
      return View(genres);
    }

    public ActionResult Genre(string genre)
    {
      var model = new MovieGenreViewModel(genre);
      if (model.Genre == null)
        return HttpNotFound();

      return View(model);
    }

    public ActionResult GenreCover(string genre, int width = 0, int height = 0)
    {
      return Images.ReturnFromService(WebMediaType.MovieGenre, genre, WebFileType.Cover, width, height, "Images/default/genre-cover.png");
    }

    public ActionResult GenreFanart(string genre, int width = 0, int height = 0, int num = -1)
    {
      return Images.ReturnFromService(WebMediaType.MovieGenre, genre, WebFileType.Backdrop, width, height, "Images/default/genre-fanart.png", num);
    }
  }
}

Applications/MPExtended.Applications.WebMediaPortal/Views/MovieLibrary/Details.cshtml
@model MovieViewModel
@{
    ViewBag.Title = Model.Movie.Title;
}

<h2>@Model.Movie.Title</h2>

<div class="imageColumn">
    <img src="@Url.Action("Cover", new { movie = @Model.Id, width = 300 })" width="300" alt="No image" />
</div>

<div class="dataColumn">
    <ul>
        <li>@Model.Movie.Year</li>
        <li>@String.Join(", ", Model.Movie.Genres)</li>
        <li>@UIStrings.Rating: @Model.Movie.Rating.ToString("##.0")</li>
        <li>@Model.Quality, @Model.Movie.Runtime min.<br /></li>
    </ul>
    <br />
    <ul>
        <li>@Html.ActionLink(UIStrings.Download, "Download", "Stream", Skin.GetDownloadArguments(Model.Movie.Type, Model.Movie.Id), new { })</li>
        <li>@Html.ActionLink(UIStrings.Play, "Play", new { movie = Model.Id })</li>
    </ul>
</div>

<div class="textColumn">
    @UIStrings.Tagline: @Model.Movie.Tagline
    <br />
    <br />
    @Model.Movie.Summary
</div>

Applications/MPExtended.Applications.WebMediaPortal/Views/MovieLibrary/Index.cshtml
@model IEnumerable<MovieViewModel>
@{
    ViewBag.Title = UIStrings.Movies;
}
@Html.Assets().AddViewStylesheet("MovieLibrary/Movie.css")

<h2>@UIStrings.YourMovies</h2>


<div id="slider" style="clear:both;float:left"></div>

@{ 
    var count = 0;
    var pages = 1;
}

<div class="paged-data-container">

    @foreach (var movie in Model)
    {
        if ((count % MPExtended.Applications.WebMediaPortal.Code.Settings.ActiveSettings.PageSize) == 0)
        {
            if (count > 0) { pages++; }
        }
        count++;
    
        <div class="movieContainer @("page" + pages.ToString())" >
            <div>
            <a href="@Url.Action("Details", "MovieLibrary", new { movie = movie.Id })" class="movieTitle">
                <p>@( movie.Movie.Title.Length > 62 ? movie.Movie.Title.Substring(0, 61) + "..." : movie.Movie.Title)</p>
            </a>
            <a href="@Url.Action("Details", "MovieLibrary", new { movie = movie.Id })" class="movieImage">
                <span style="width:100px;height:155px" class="async-image-display" data-alt="@movie.Movie.Title Cover" data-src="@Url.Action("Cover", "MovieLibrary", new { movie = movie.Id, width = 100 })"></span>
            </a>
            <a href="@Url.Action("Play", "MovieLibrary", new { movie = movie.Id })" class="movieControls">
                <img height="16" width="12" src="@Url.ContentLink("Images/btnPlay.png")" />
            </a>                
            <p style="margin: 2px;">@movie.Movie.Genres.FirstOrDefault()</p>
            <p style="margin: 2px;">@movie.Movie.Runtime min.</p>
                </div>
        </div>
    
    }

</div>

@Html.jQuery().EnableRangeSlider(pages, "#slider", UIStrings.SelectPage)
@Html.jQuery().EnableImageLoading()

Applications/MPExtended.Applications.WebMediaPortal/Views/MovieLibrary/Play.cshtml
@model MovieViewModel
@{
	ViewBag.Title = String.Format(UIStrings.WatchingMovie, Model.Movie.Title);
}

<h2>@UIStrings.Play</h2>
@Html.Raw(String.Format(UIStrings.YouAreWatchingMovie, Model.Movie.Title))
<br />

@{
    Html.RenderAction("Player", "Stream", new
    {
        type = MPExtended.Services.Common.Interfaces.WebMediaType.Movie,
        itemId = @Model.Id
    });
}